# Generated by Django 4.0 on 2021-12-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('eng_name', models.CharField(max_length=10)),
                ('introduce', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('wpage', models.CharField(max_length=100)),
            ],
        ),
    ]
