# Generated by Django 4.0 on 2021-12-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('pic', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('youtube', models.CharField(max_length=200)),
                ('wtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.type')),
            ],
        ),
    ]
