# Generated by Django 4.0 on 2021-12-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
