# Generated by Django 4.0 on 2021-12-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='pimage/'),
        ),
    ]
