# Generated by Django 4.0 on 2021-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_work_picprd_work_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='picprd',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='work',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
