# Generated by Django 4.0 on 2022-01-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_profile_d_pimage_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='picprd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.CharField(max_length=50),
        ),
    ]
